### PR TITLE
Azure CLI syntax updates

### PR DESCRIPTION
**Pull request by TimShererWithAquent**
[1970076](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1970076)

@dbradish-microsoft I don't work in the samples repos often, but I think I'm making this change in the right place -

### CODE REVIEW

**Comment by dbradish-microsoft** [comment]
@TimShererWithAquent , all updates made to this repo are overwritten.  The copied work item has a note --> ​"Note! The MicrosoftDocs/Samples repo cannot be modified.  You need to trace the GitHub source code to find the actual source located somewhere else.  Edits to the Samples repo itself will be overwritten." which I'm not sure if also applies here.  Unless ... is this the source for MicrosoftDocs/Samples?

**Comment by TimShererWithAquent** [comment]
#sign-off

**Comment by TimShererWithAquent** [comment]
Hi @ericmitt - I'm trying to find out who owns this repo. Do you know who I can contact about this PR? Thanks

**Comment by TimShererWithAquent** [comment]
@dominicbetts - I'm trying to find out who owns this repo. Do you know who I can contact about this PR? Thanks

**Comment by dominicbetts** [comment]
Hi @TimShererWithAquent - @ericmitt has left Microsoft. I'm going to see if I can take ownership of this repo and then merge the PR.

**Review by rido-min — APPROVED** [review]

**Pull request merged**
